/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import floor2GltfFile from './tempFloor2.gltf';

import gsap from 'gsap';

export default function Model({ isVisible = true, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(floor2GltfFile);

  useEffect(() => {
    !isVisible
      ? gsap.to(group.current.position, { y: 15, duration: 2 })
      : gsap.to(group.current.position, { y: 0, duration: 0.5 });
  }, [isVisible]);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Wall.geometry}
        material={materials['Material.001']}
        position={[0.87, 0, -1.74]}
      />
    </group>
  );
}

useGLTF.preload(floor2GltfFile);
