/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import floor_1GltfFile from './floor_1.gltf';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(floor_1GltfFile);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Wall.geometry}
        material={materials['Material.001']}
        position={[0.87, 0, -1.74]}
      />
    </group>
  );
}

useGLTF.preload(floor_1GltfFile);
