/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { memo } from 'react';
import { useGLTF } from '@react-three/drei';
import floorGltf from './Floor_1.gltf';

function Floor_1() {
  const { nodes, materials } = useGLTF(floorGltf);

  return (
    <group scale={[1, 1, 1]} dispose={null}>
      <mesh
        geometry={nodes.Wall124.geometry}
        material={materials.Wall}
        position={[-11.82, 0, 2.98]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall123.geometry}
        material={materials.Wall}
        position={[0.3, 0, 1.11]}
      />
      <mesh
        geometry={nodes.Wall122.geometry}
        material={materials.Wall}
        position={[0.58, 0, -1.02]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall121.geometry}
        material={materials.Wall}
        position={[0.58, 0, -0.31]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall120.geometry}
        material={materials.Wall}
        position={[0.58, 0, 0.08]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall119.geometry}
        material={materials.Wall}
        position={[0.58, 0, 0.47]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall118.geometry}
        material={materials.Wall}
        position={[0.58, 0, 1.15]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall117.geometry}
        material={materials.Wall}
        position={[0.02, 0, 1.52]}
      />
      <mesh
        geometry={nodes.Wall116.geometry}
        material={materials.Wall}
        position={[-0.28, 0, -1.75]}
      />
      <mesh
        geometry={nodes.Wall114.geometry}
        material={materials.Wall}
        position={[0.06, 0, 2.67]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall113.geometry}
        material={materials.Wall}
        position={[-0.32, 0, 2.13]}
      />
      <mesh
        geometry={nodes.Wall111.geometry}
        material={materials.Wall}
        position={[-1.94, 0, 2.67]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall110.geometry}
        material={materials.Wall}
        position={[-1.94, 0, 1.89]}
      />
      <mesh
        geometry={nodes.Wall030.geometry}
        material={materials.Wall}
        position={[-1.94, 0, 1.85]}
      />
      <mesh
        geometry={nodes.Wall027.geometry}
        material={materials.Wall}
        position={[0.16, 0, 3.32]}
      />
      <mesh
        geometry={nodes.Wall023.geometry}
        material={materials.Wall}
        position={[-1.46, 0, 1.88]}
      />
      <mesh
        geometry={nodes.Wall021.geometry}
        material={materials.Wall}
        position={[0.06, 0, 1.7]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Wall017.geometry}
        material={materials.Wall}
        position={[-6.78, 0, 2.99]}
      />
      <mesh
        geometry={nodes.Wall016.geometry}
        material={materials.Wall}
        position={[-7.87, 0, 2.99]}
      />
      <mesh
        geometry={nodes.Wall014.geometry}
        material={materials.Wall}
        position={[-10.16, 0, 2.3]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Wall013.geometry}
        material={materials.Wall}
        position={[-11.81, 0, 3.47]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall011.geometry}
        material={materials.Wall}
        position={[-10.75, 0, 1.01]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall010.geometry}
        material={materials.Wall}
        position={[-10.75, 0, 2.01]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall007.geometry}
        material={materials.Wall}
        position={[-11.81, 0, 1.5]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall006.geometry}
        material={materials.Wall}
        position={[-11.81, 0, 0.24]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall.geometry}
        material={materials.Wall}
        position={[-11.81, 0, -1.51]}
      />
      <mesh
        geometry={nodes.Wall005.geometry}
        material={materials.Wall}
        position={[-11.45, 0, 2.98]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Wall008.geometry}
        material={materials.Wall}
        position={[-10.54, 0, 4.45]}
      />
      <mesh
        geometry={nodes.Wall009.geometry}
        material={materials.Wall}
        position={[-6.78, 0, 3.39]}
      />
      <mesh
        geometry={nodes.Wall138.geometry}
        material={materials.Wall}
        position={[-0.94, 0, 1.89]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Wall115.geometry}
        material={materials.Wall}
        position={[-0.43, 0, 1.89]}
        rotation={[0, -1.57, 0]}
      />
      <mesh
        geometry={nodes.Wall139.geometry}
        material={materials.Wall}
        position={[-0.98, 0, 3.31]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        geometry={nodes.Wall141.geometry}
        material={materials.Wall}
        position={[-0.52, 0, 3.31]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        geometry={nodes.Wall112.geometry}
        material={materials.Wall}
        position={[-0.52, 0, 2.67]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials.Ground}
        position={[-0.06, 0.01, 0.09]}
        scale={[11.8, 1, 4.42]}
      />
      <mesh
        geometry={nodes.Stairs008.geometry}
        material={nodes.Stairs008.material}
        position={[-10.26, 0.15, 2.31]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.28, 0.05, 0.09]}
      />
      <mesh
        geometry={nodes.Stairs002.geometry}
        material={nodes.Stairs002.material}
        position={[-10.65, 0.02, 2.66]}
        scale={[0.28, 0.05, 0.09]}
      />
      <mesh
        geometry={nodes.Wall034.geometry}
        material={nodes.Wall034.material}
        position={[-11.68, 0.13, -0.98]}
        scale={[0.7, 0.11, -0.89]}
      />
      <group
        position={[-11.36, 0.02, -0.86]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.15, 0.05, -0.07]}
      >
        <mesh
          geometry={nodes.Stairs007.geometry}
          material={nodes.Stairs007.material}
        />
        <mesh
          geometry={nodes.Stairs007_1.geometry}
          material={nodes.Stairs007_1.material}
        />
        <mesh
          geometry={nodes.Stairs007_2.geometry}
          material={nodes.Stairs007_2.material}
        />
        <mesh
          geometry={nodes.Stairs007_3.geometry}
          material={nodes.Stairs007_3.material}
        />
        <mesh
          geometry={nodes.Stairs007_4.geometry}
          material={nodes.Stairs007_4.material}
        />
        <mesh
          geometry={nodes.Stairs007_5.geometry}
          material={nodes.Stairs007_5.material}
        />
        <mesh
          geometry={nodes.Stairs007_6.geometry}
          material={nodes.Stairs007_6.material}
        />
        <mesh
          geometry={nodes.Stairs007_7.geometry}
          material={nodes.Stairs007_7.material}
        />
      </group>
      <group
        position={[-11.63, 0.16, -0.63]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.15, 0.05, -0.07]}
      >
        <mesh
          geometry={nodes.Stairs011.geometry}
          material={nodes.Stairs011.material}
        />
        <mesh
          geometry={nodes.Stairs011_1.geometry}
          material={nodes.Stairs011_1.material}
        />
        <mesh
          geometry={nodes.Stairs011_2.geometry}
          material={nodes.Stairs011_2.material}
        />
        <mesh
          geometry={nodes.Stairs011_3.geometry}
          material={nodes.Stairs011_3.material}
        />
        <mesh
          geometry={nodes.Stairs011_4.geometry}
          material={nodes.Stairs011_4.material}
        />
        <mesh
          geometry={nodes.Stairs011_5.geometry}
          material={nodes.Stairs011_5.material}
        />
        <mesh
          geometry={nodes.Stairs011_6.geometry}
          material={nodes.Stairs011_6.material}
        />
        <mesh
          geometry={nodes.Stairs011_7.geometry}
          material={nodes.Stairs011_7.material}
        />
      </group>
      <mesh
        geometry={nodes.Wall039.geometry}
        material={materials.Wall}
        position={[0.16, -0.01, -4.42]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.45, 1.03, 0.7]}
      />
      <mesh
        geometry={nodes.Wall038.geometry}
        material={nodes.Wall038.material}
        position={[-0.29, 0.13, 2.51]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.65, 0.11, -0.59]}
      />
      <mesh
        geometry={nodes.Stairs014.geometry}
        material={nodes.Stairs014.material}
        position={[-0.22, 0.02, 2.19]}
        scale={[0.15, 0.05, -0.07]}
      />
      <mesh
        geometry={nodes.Stairs013.geometry}
        material={nodes.Stairs013.material}
        position={[0.01, 0.16, 2.46]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.15, 0.05, -0.07]}
      />
      <mesh
        geometry={nodes.Wall040.geometry}
        material={materials.Wall}
        position={[-2.19, -0.01, 1.82]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.45, 1.03, 0.7]}
      />
      <mesh
        geometry={nodes.Wall018.geometry}
        material={materials.Wall}
        position={[-4.58, 0, 2.28]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.Wall}
        position={[-4.4, 0.28, 2.58]}
        scale={[2.43, 1, 4.27]}
      />
      <mesh
        geometry={nodes.Wall012.geometry}
        material={materials.Wall}
        position={[-10.75, 0, 0.02]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall004.geometry}
        material={materials.Wall}
        position={[-10.84, -0.01, 2.74]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Wall002.geometry}
        material={materials.Wall}
        position={[-10.16, 0, -1.03]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall003.geometry}
        material={materials.Wall}
        position={[-11.22, 0, -0.44]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Wall001.geometry}
        material={materials['Wall.001']}
        position={[-4.56, 0, 2.29]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Stairs005.geometry}
        material={nodes.Stairs005.material}
        position={[-6.9, 0.04, 2.76]}
        scale={[0.17, 0.1, 0.04]}
      />
      <mesh
        geometry={nodes.Stairs003.geometry}
        material={nodes.Stairs003.material}
        position={[-7.79, 0.04, 2.76]}
        scale={[0.17, 0.1, 0.04]}
      />
      <mesh
        geometry={nodes.Wall020.geometry}
        material={materials['Wall.002']}
        position={[-7.87, 0, 2.58]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall022.geometry}
        material={nodes.Wall022.material}
        position={[-10.75, 0.13, 2.26]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1, 0.11, 1]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-7.35, 0.29, 2.33]}
      />
      <mesh
        geometry={nodes.Wall028.geometry}
        material={materials['Wall.004']}
        position={[-11.82, 0, -0.53]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        geometry={nodes.Wall015.geometry}
        material={materials['Wall.003']}
        position={[-10.16, 0, -0.53]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Wall019.geometry}
        material={materials['Wall.008']}
        position={[-4.4, 0, 2.84]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.45, -1.03, -0.7]}
      />
      <group
        position={[-4.48, -0.02, 2.52]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.18, 0.12, 0.07]}
      >
        <mesh
          geometry={nodes.Stairs001.geometry}
          material={nodes.Stairs001.material}
        />
        <mesh
          geometry={nodes.Stairs001_1.geometry}
          material={nodes.Stairs001_1.material}
        />
        <mesh
          geometry={nodes.Stairs001_2.geometry}
          material={nodes.Stairs001_2.material}
        />
        <mesh
          geometry={nodes.Stairs001_3.geometry}
          material={nodes.Stairs001_3.material}
        />
        <mesh
          geometry={nodes.Stairs001_4.geometry}
          material={nodes.Stairs001_4.material}
        />
        <mesh
          geometry={nodes.Stairs001_5.geometry}
          material={nodes.Stairs001_5.material}
        />
        <mesh
          geometry={nodes.Stairs001_6.geometry}
          material={nodes.Stairs001_6.material}
        />
        <mesh
          geometry={nodes.Stairs001_7.geometry}
          material={nodes.Stairs001_7.material}
        />
      </group>
      <group position={[0.25, 0, -0.66]}>
        <mesh
          geometry={nodes.Wall012_1.geometry}
          material={materials['Wall.005']}
        />
        <mesh
          geometry={nodes.Wall012_2.geometry}
          material={materials['Wall.006']}
        />
      </group>
      <mesh
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[0, 0.12, 0]}
        scale={21.62}
      />
    </group>
  );
}

export default memo(Floor_1);

useGLTF.preload(floorGltf);
