/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import floor from './tempFloor.gltf';
export default function Model({ ...props }) {
  const group = useRef();
  const { nodes } = useGLTF(floor);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[10.43, 1.92, 0.03]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-0.05, 1.92, 7.53]}
        scale={[0.97, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[0.2, 1.94, -7.55]}
        scale={[0.97, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-10.5, 1.89, 0.05]}
      />
    </group>
  );
}

useGLTF.preload(floor);
