/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import gltf from './tempFloor.gltf';
import RoomNumber from '../RoomNumbers/RoomNumber';
export default function Model({ roomsLocations, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(gltf);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, Math.PI]} scale={[20.03, 0.99, 22.44]}>
        <mesh
          geometry={nodes.Cube017.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Cube017_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      {roomsLocations.map((room, index) => (
        <RoomNumber key={index} {...room} />
      ))}
    </group>
  );
}

useGLTF.preload(gltf);
